### ISSUE TITLE
Use emoji reaction instead of comments

### ISSUE THREAD

**Issue by aslafy-z** [alexellis/comment-vibes#1]
I just created a feature request to add events for reaction_created, reaction_deleted.
Here's the post, it may be interesting for you to followup on it: https://github.community/t5/GitHub-Actions/Feature-request-Emoji-reaction-event/td-p/49738

**Comment by alexellis** [comment]
I did a search and read the API docs before creating the example, it would have been nice if GitHub had reactions in their API, but it's just comments for now.

**Comment by alexellis** [comment]
Feel free to comment on https://github.com/teamserverless/proposals/issues/1 and you can see the live data at http://206.189.126.36/function/view
